clear; clc; close all;

SENS_VARIANTS = { ...
    'central',              ... % all central / literature values
    'epsRfloor_low',        ... 
    'omegaNI_slow',         ... 
    'omegaR_fast',          ... 
    'epsRdeath_low',        ... 
    'behav_weak',           ... 
    'behav_strong',         ... 
    'behav_caseweighted',   ... 
    'behav_tau_short',      ... 
    'noise_persistent'      ... 
    };

SENS_RESULTS = [];   % accumulated inside ModelMain.m

for SENS_IDX = 1:numel(SENS_VARIANTS)
    SENS_VARIANT = SENS_VARIANTS{SENS_IDX};
    fprintf('\n\n##################################################\n');
    fprintf('  SENSITIVITY RUN %d/%d : %s\n', SENS_IDX, numel(SENS_VARIANTS), SENS_VARIANT);
    fprintf('##################################################\n');

    ModelMain;        % preserves SENS_* via its own clearvars; appends to SENS_RESULTS
    close all;    % don't accumulate figure windows across runs
end

fprintf('\n\n===== SENSITIVITY SWEEP COMPLETE =====\n');
disp(SENS_RESULTS);
writetable(SENS_RESULTS, 'Sensitivity_Summary.csv');
fprintf('Written to Sensitivity_Summary.csv\n\n');

if height(SENS_RESULTS) > 1
    fprintf('Headline robustness across %d variants:\n', height(SENS_RESULTS));
    fprintf('  high-hesitancy CASE  ratio: %.2fx  (range %.2f - %.2f)\n', ...
        median(SENS_RESULTS.highhes_case_ratio), ...
        min(SENS_RESULTS.highhes_case_ratio), max(SENS_RESULTS.highhes_case_ratio));
    fprintf('  high-hesitancy DEATH ratio: %.2fx  (range %.2f - %.2f)\n', ...
        median(SENS_RESULTS.highhes_death_ratio), ...
        min(SENS_RESULTS.highhes_death_ratio), max(SENS_RESULTS.highhes_death_ratio));
    fprintf(['\nReport these as RANGES. A narrow range = the conclusion is robust to\n' ...
             'the parameters evidence does not pin; a wide one = it is not, and the\n' ...
             'claim must be qualified accordingly.\n']);
end
